jirum-alarm/jirum-alarm-frontend

src/app/alarm/components/AlarmList.tsx
src/app/alarm/hooks/useNotificationsViewModel.ts

resolve #173
- 알림 리스트 api에 offset, limit 전달
- 무한 스크롤 대응
offset 넘겨주는 구현을 아직 데이터가 정립이 안된 것 같아서 추후에 백이랑 api 맞춰가면 될 것 같슴당
- 개발 환경, 아직 데이터가 음서서 나중에 추가 확인하면 좋을 것 같슴당
https://github.com/jirum-alarm/jirum-alarm-frontend/assets/50096419/b87a5a02-b033-4bb3-9cf7-8cebee7aaa08
- 모킹 데이터로 값 불러오는지 확인

[fix] 알림 리스트 페이지 api 수정

---

src/app/alarm/components/AlarmItem.tsx

title이 아니라 message를 사용해서 변경합니다!

[fix] 알림 리스트 표시 수정

---

src/app/login/email/components/EmailLoginForm.tsx

- 로그인 페이지의 bottom fixed 버튼 스타일을 제거했습니다.
- ios앱에서 focus시 button 숨김처리되는 로직을 제거했습니다.
- 회원가입 페이지 등에서 input이 하나만 존재하는 ui는 bottom fixed를 그대로 유지했습니다.
https://github.com/jirum-alarm/jirum-alarm-frontend/assets/89559826/394c9990-99e6-4dfb-b6f2-499aad091149

[style] 로그인 페이지 bottom fixed 버튼 스타일 제거

---

next.config.js
package.json
pnpm-lock.yaml
src/app/(home)/components/ProductList.tsx
src/app/(home)/components/ProductRecommendation.tsx
src/app/(home)/hooks/useProductListViewModel.ts
src/graphql/interface/product.ts
src/graphql/product.ts
src/hooks/useScreenSize.ts
tailwind.config.js

- 홈 화면 전체 탭 디자인 수정
- 상위 섹션 최신 상품들
- 핫딜 상품
- 이후의 최신 상품들
https://jirum-alarm-frontend-81ewmcrkr-jirumalarms-projects.vercel.app/

[feature] 홈 화면 개편 

---

src/app/(home)/components/ProductRecommendation.tsx

상품 이미지 없는 경우 처리했습니당
- 이미지 링크가 api 레스폰스에 없는 경우
- 이미지 링크가 api 레스폰스에 있지만 실제 불러올 때 실패하는 경우
공통 컴포넌트로 처리는 나중에 고민해볼게영

[fix] 상품 이미지 없는 경우 처리

---

src/app/(home)/components/ProductList.tsx
src/app/(home)/components/ProductRecommendation.tsx
src/app/(home)/hooks/useProductListViewModel.ts
src/app/search/components/RecentKeywords.tsx
src/app/search/components/RecommendationKeywords.tsx
src/app/search/components/RecommendationProduct.tsx
src/app/search/hooks/useProductListViewModel.ts
src/app/search/hooks/useSearchInputViewModel.ts

- 이벤트 변경
- 페이지 기록 추가
- 이벤트 추가 
- 카테고리 확인
- 키워드 클릭

[chore] 이벤트 트래킹 추가

---

package.json
pnpm-lock.yaml
src/app/(home)/components/ProductList.tsx
src/app/(home)/components/ProductRecommendation.tsx
src/app/(home)/components/SearchInput.tsx
src/app/(home)/hooks/useProductListViewModel.ts
src/app/search/components/ProductList.tsx
src/app/search/components/RecentKeywords.tsx
src/app/search/components/RecommendationKeywords.tsx
src/app/search/components/SearchInput.tsx
src/app/search/hooks/useProductListViewModel.ts
src/app/search/hooks/useSearchInputViewModel.ts
src/app/search/page.tsx
src/constants/mixpanel.ts

- 이벤트 변수 상수화
- 검색 페이지
- 페이지 이동 클라이언트에서 라우팅
- 추천 검색어 검색 후에도 고정
- 검색어 초기화 버튼 키워드 입력된 경우 표시
- 검색바 스크롤 상/하에 맞게 표시/비표시
- 페이지 최대 넓이 홈이랑 같게 변경
- 추천 검색어 추가

[feature] 검색 페이지 개선

---

src/app/search/components/SearchInput.tsx
src/app/search/hooks/useProductListViewModel.ts
src/app/search/hooks/useSearchInputViewModel.ts
src/app/search/page.tsx

- 검색 헤더 바 크기 조정
- 인풋이 비게되면 키워드 보이는 초기 검색화면으로 돌아감
- 검색어 초기화시 초기 검색화면으로 이동
- 검색 헤더바 크기가 제대로 동작
https://github.com/jirum-alarm/jirum-alarm-frontend/assets/50096419/4612e644-f8f9-44d5-89bf-4b21a1096407

[feature] 검색 페이지 헤더바 개선

---

apps/web/src/app/(home)/components/ProductRecommendation.tsx
apps/web/src/features/products/components/ProductImageCard.tsx
apps/web/src/util/displayTime.ts

상품 등록 시각 추가

---

apps/admin/src/app/auth/signin/components/SigninPage.tsx
apps/admin/src/app/auth/signin/page.tsx
apps/admin/src/components/Layouts/DefaultLayout.tsx
apps/admin/src/components/Sidebar/index.tsx

- 로그인 페이지에서 sidebar보이는 레이아웃 제거

style(admin): 로그인 페이지 레이아웃 변경

---

apps/admin/package.json
apps/admin/src/app/hotdeal/keyword/components/HotdealKeywordsTable.tsx
apps/admin/src/app/hotdeal/keyword/components/HotdealKeywordsTableSkeleton.tsx
apps/admin/src/graphql/keyword.ts
apps/admin/src/hooks/graphql/keyword.ts
apps/admin/src/types/keyword.ts
apps/admin/src/utils/date.ts
pnpm-lock.yaml

- 키워드 목록에 업데이트 시간 표시하는 컬럼 추가
- 정렬조건을 가중치 높은 순으로 변경

feature(admin): 키워드 목록 정렬조건 변경 및 컬럼 추가

---

apps/admin/src/components/Layouts/DefaultLayout.tsx
apps/admin/src/components/Sidebar/index.tsx

- 100vh 스타일 제거
- sidebar 컴포넌트의 position을 무조건 fixed로 변경

style(admin): 어드민 레이아웃 버그 수정

---

apps/web/src/app/products/[id]/page.tsx

feature(web): 상품 상세 페이지 메타데이터 추가

---

apps/web/schema.graphql
apps/web/src/app/products/[id]/components/PopularProudcts.tsx
apps/web/src/graphql/interface/product.ts
apps/web/src/graphql/product.ts
apps/web/src/shared/api/gql/gql.ts
apps/web/src/shared/api/gql/graphql.ts

product 의 category -> categoryName 으로 변경

fix(web): 상품 상세 하단 카테고리명 변경

---

apps/web/src/app/trending/components/trending-container/index.tsx

- 바텀 바 애니메이션
- misc.
- 기존 라이브러리 사용시 변경에 어려워 react-tabs대신 직접 구현했습니다. 
- N/A
https://github.com/user-attachments/assets/d4016f67-8a88-4227-9eeb-f3d6323df45f

style(web): 카테고리 탭 바텀바 애니메이션 추가

---

apps/web/schema.graphql
apps/web/src/app/(home)/components/(home)/HomeContainerV2.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/ProductImageCardList.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/RecommendedProductContainer.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/RecommendedProductContainerServer.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/RecommendedProductList.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/RecommendedProductTabs.tsx
apps/web/src/app/recommend/components/RecommendContainer.tsx
apps/web/src/app/recommend/components/RecommendPageHeader.tsx
apps/web/src/app/recommend/components/RecommendProductList.tsx
apps/web/src/app/recommend/components/RecommendedProductTabsFetcher.tsx
apps/web/src/app/recommend/page.tsx
apps/web/src/app/trending/components/trending-container/index.tsx
apps/web/src/assets/icons/arrow_left.svg
apps/web/src/components/common/icons/ArrowLeft.tsx
apps/web/src/components/layout/BackButton.tsx
apps/web/src/components/layout/BasicLayout.tsx
apps/web/src/constants/mixpanel.ts
apps/web/src/constants/page.ts
apps/web/src/entities/product/product.queries.ts
apps/web/src/graphql/product.ts
apps/web/src/shared/api/gql/gql.ts
apps/web/src/shared/api/gql/graphql.ts
apps/web/src/shared/api/product/product.service.ts

feature(web): 지름알림 추천 페이지 작업

---

apps/mobile/App.tsx
apps/mobile/android/gradle.properties
apps/mobile/ios/Podfile.lock
apps/mobile/package.json
pnpm-lock.yaml

feature(mobile): react-native webview 적용

---

apps/web/src/app/(home)/components/(home)/AppDownloadCTA.tsx
apps/web/src/app/(home)/components/(home)/JirumRankingContainer.tsx
apps/web/src/app/(home)/components/(home)/LiveHotDealContainer.tsx
apps/web/src/app/(home)/components/(home)/RecommendedProduct/RecommendedProductContainer.tsx
apps/web/src/app/(home)/components/(search)/RecentKeywords.tsx
apps/web/src/app/(home)/components/(search)/RecommendationKeywords.tsx
apps/web/src/app/(home)/components/(search)/SearchInput.tsx
apps/web/src/app/policies/privacy/components/PrivacyPolicy.tsx
apps/web/src/app/policies/terms/components/TermsOfUse.tsx
apps/web/src/app/products/[id]/components/CommunityReaction.tsx
apps/web/src/app/products/[id]/components/NoticeProfitUrl.tsx
apps/web/src/app/products/[id]/components/PopularProducts.tsx
apps/web/src/app/products/[id]/components/ProductDetailLayout.tsx
apps/web/src/app/products/[id]/components/RecommendButton.tsx
apps/web/src/app/products/[id]/components/RelatedProductsContainer.tsx
apps/web/src/app/signup/page.tsx
apps/web/src/components/SectionHeader.tsx
apps/web/src/components/layout/BackButton.tsx
apps/web/src/components/layout/BasicLayout.tsx

- 발견된 디자인 어긋난 부분들 수정
- 섹션헤더 컴포넌트화

fix(web): 새로운 디자인 QA 반영

---

apps/web/src/app/(desktop-ready)/components/desktop/DesktopGNB.tsx
apps/web/src/app/(desktop-ready)/layout.tsx
apps/web/src/components/common/Logo/LogoLink.tsx

pc classname이 GNB를 커버 못하게 되어있었어서 수정했습니다

fix(web): pc ui 적용 범위 조정

---

apps/web/src/app/actions/agent.ts

앱에서 커스텀 useragent 사용하는거 대응했습니다

HOTFIX(web): 모바일/데스크탑 분기조건 수정

---

.github/workflows/deploy-web-prod.yml
.github/workflows/deploy-web-staging.yml
apps/web/deploy/development/Dockerfile
apps/web/deploy/production/Dockerfile
apps/web/src/app/(app)/providers/appProvier.tsx
apps/web/src/constants/env.ts
apps/web/src/constants/graphql.ts

- **왜**: 기존 CI/CD 파이프라인의 성능, 보안, 유지보수성 개선 필요
- **무엇**: Docker 빌드 현대화, GitHub Actions 최적화, 보안 스캔 추가로 배포 파이프라인 전면 개편
- **Node.js 22 + pnpm 10**: 최신 런타임 및 패키지 매니저로 업그레이드
- **Docker 멀티스테이지 빌드**: deps/builder/pruner/runner 단계로 분리하여 이미지 크기 최적화
- **GitHub Actions 현대화**: Docker Buildx, 캐시 최적화, 환경별 배포 분리
- **보안 강화**: Trivy 취약점 스캔, SARIF 업로드, 비 root 사용자 실행
- **yq 기반 K8s 배포**: Perl 기반 문자열 치환을 구조화된 YAML 업데이트로 대체
1. 경로/화면: GitHub Actions 워크플로우
2. 재현 절차: 
- main 브랜치 푸시 시 스테이징 자동 배포
- 태그 생성 시 프로덕션 배포  
- Security 탭에서 Trivy 스캔 결과 확인
3. 기대 결과: 
- 빌드 시간 단축 및 캐시 활용
- 보안 취약점 자동 감지
- 더 작고 안전한 Docker 이미지 생성

chore(ci,web): CI/CD 파이프라인 현대화 및 보안 강화

---

apps/web/src/app/(desktop-ready)/(home)/components/HomeContainerV2.tsx
apps/web/src/app/(desktop-ready)/products/[id]/components/mobile/ProductDetailPage.tsx
apps/web/src/app/(desktop-ready)/products/[id]/layout.tsx
apps/web/src/app/(desktop-ready)/trending/components/TabbarV2.tsx
apps/web/src/app/(desktop-ready)/trending/components/trending-container/index.tsx
apps/web/src/app/(desktop-ready)/trending/layout.tsx
apps/web/src/components/layout/BasicLayout.tsx
apps/web/src/features/product-detail/components/CommunityReaction.tsx
apps/web/src/features/product-detail/components/HotdealGuide.tsx
apps/web/src/features/product-detail/components/HotdealScore.tsx
apps/web/src/features/products/carousel/CarouselProductList.tsx
apps/web/src/features/products/carousel/CarouselProductListSkeleton.tsx
apps/web/src/features/products/carousel/CarouselProductsSection.tsx
apps/web/src/shared/ui/DisplayPrice.tsx
apps/web/src/widgets/live-hotdeal/LiveHotDealSection.tsx
apps/web/src/widgets/recommend/RecommendedProductSection.tsx
apps/web/src/widgets/recommend/RecommendedProductTabs.tsx
apps/web/src/widgets/search/SearchPage.tsx
apps/web/src/widgets/search/components/InitialResult.tsx
apps/web/src/widgets/search/components/ProductNotFound.tsx
apps/web/src/widgets/search/components/SearchResult.tsx

[feat] 반응형 레이아웃 개선 및 UI 최적화
모바일/데스크톱 간 일관된 사용자 경험 제공을 위한 반응형 레이아웃 개선 및 UI 구조 최적화
- **검색 페이지**: 검색 결과 레이아웃 패딩 최적화, ProductNotFound 컴포넌트에 SectionHeader 적용
- **홈페이지**: overflow-x-hidden 처리로 가로 스크롤 방지, 반응형 패딩 개선
- **캐러셀 컴포넌트**: slidesOffsetBefore 일관성 개선, 스켈레톤 패딩 추가
- **상품 상세 페이지**: PC 버전 타이틀 폰트 크기 통일, 모바일 하단 섹션 마진 추가
- **트렌딩 페이지**: TabbarV2 PC 상단 위치 개선, 탭 변경 시 스크롤 최상단 이동 추가
1. **검색 페이지**: `/search` → 검색어 입력 → 결과 없음 화면 확인
2. **홈페이지**: `/` → 추천 섹션 및 실시간 핫딜 캐러셀 동작 확인
3. **상품 상세**: `/products/[id]` → PC/모바일 레이아웃 비교
4. **트렌딩**: `/trending` → 탭 전환 시 스크롤 동작 확인
- 성능: 가로 스크롤 방지로 렌더링 성능 개선, 탭 애니메이션 stiffness 향상 (100→300)
- 접근성: SectionHeader 적용으로 구조적 접근성 향상
- 호환성: 모바일/데스크톱 반응형 지원 강화
- 브레이킹 체인지: N
- 리스크: 레이아웃 변경으로 인한 일부 화면에서의 스타일 깨짐 가능성
- 완화책: 기존 클래스 구조 유지하며 점진적 개선 적용
- 롤백 계획: 각 커밋이 기능별로 분리되어 있어 개별 롤백 …

[feat] 반응형 레이아웃 개선 및 UI 최적화
